# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c54ff7081d068c7cb6bf38cecbdc0a871daf5bc4b1a9e07e282dca47279bc91e905f07e2332a1df0884535dee66916bdfb0489168bb36faa003549e08526b13a

test:
  secret_key_base: 225c10024e12b969a23ff61f0fe3e6159db1a676f8229a3226a0c4e611a615bece0375917cc02c02a219ff92ac9bec03ca2057b63e948ab604b33ecd2f156322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
